import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import useInterval from '@/components/hook/useInterval'
import {useEffect, useState} from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const currentTime = useInterval(new Date());
  
  const {hours,minutes,seconds} = currentTime;

  //prevent hydration error
  const [screen, setScreen] = useState(false);

  useEffect(()=>{
     setScreen(true)
  },[])
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        

        {
          screen && 
          <div className={styles.center}>
          
          <h1>Updating time every 10 seconds:
           {hours}
          :{minutes}
          :{seconds}
          </h1>
         </div>
        }

       
      </main>
    </>
  )
}
